### ISSUE TITLE
Vienna must have a memory leak

### ISSUE THREAD

**Issue by jimrome** [ViennaRSS/vienna-rss#545] opened 2015-11-20 14:34 UTC
Version 3.0.9 :22b3ce2 is using humongous amounts of memory on my MacPro. It just got up to 5.6GB and forced my Mac to a crawl. I have 48 GB of memory installed!.
And none of the 5.6GB is compressed.

**Comment by josh64x2** [comment] 2015-11-20 22:03
@jimrome has this happened more than once? How many feeds are you subscribed to?

**Comment by jimrome** [comment] 2015-11-20 23:22
37 feeds. It regularly gets to 2-3 GB (its 2.61 now), but has never
gotten that high before.

James A. Rome
http://jamesrome.net

**Comment by josh64x2** [comment] 2015-11-21 00:24
Can you please try https://github.com/ViennaRSS/vienna-rss/releases/download/v%2F3.1.0_beta5/Vienna3.1.0_beta5.tgz and let me know if the memory usage is still high? 
We've switch the memory management to ARC in 3.1.x.

**Comment by jimrome** [comment] 2015-11-21 13:23
It got to 4.7GB over night. I will let you know hoe the beta works.

James A. Rome
116 Claymore Lane
Oak Ridge, TN 37830-7674
865 482-5643
jamesrome@gmail.com
http://jamesrome.net

**Comment by jimrome** [comment] 2015-11-21 21:51
It is up to 2.2GB. Why don't you compress the memory?

James A. Rome
116 Claymore Lane
Oak Ridge, TN 37830-7674
865 482-5643
jamesrome@gmail.com
http://jamesrome.net

**Comment by josh64x2** [comment] 2015-11-21 22:20
The OS compresses the memory itself unfortunately.
How often do you have "Check for new articles" ? I will try and duplicate as many of your preferences as I can to see if I can debug the issue.
Do you have syncing enabled?

Thanks!

**Comment by jimrome** [comment] 2015-11-22 04:41
Every hour. No syncing.

James A. Rome
116 Claymore Lane
Oak Ridge, TN 37830-7674
865 482-5643
jamesrome@gmail.com
http://jamesrome.net

**Comment by JayBrown** [comment] 2015-11-22 11:14
I'm still on 3.0.8, and Vienna has *always* been a CPU & memory hog (checking every 30 minutes, currently 124 feeds). Can't switch to 3.0.9 or 3.1 betas, because they keep crashing (have already reported). But I'm really looking forward to better memory management.

**Comment by barijaona** [comment] 2015-11-23 00:16
To determine if it is related to refreshes or to webviews tabs, could you close all tabs and check if the behavior remains the same ?

**Comment by JayBrown** [comment] 2015-11-23 16:34
No tabs or webviews. List view, and for accessing content I only use my default browser. The app generally seems to be a bit slow, especially the quitting process is very slow. After a fresh launch, memory usually starts at around 200MB, which (I assume) might be a bit much for a simple RSS reader. (I haven't noticed the above memory increase, but then again I haven't looked for it. But I don't think that's a problem on my system.)

**Comment by josh64x2** [comment] 2015-11-23 19:48
Mine seems to start at around 95MB (that's with a 1GB database file), but upon refresh if there is a problem with a feed it does (slowly) allocate more and more memory. Will keep looking at this when I get some time.

**Comment by josh64x2** [comment] 2016-03-14 04:35
@JayBrown can you please try the [latest 3.1.0](https://github.com/ViennaRSS/vienna-rss/releases/download/v%2F3.1.0/Vienna3.1.0.tgz) release and let me know if the problem is persisting?

**Comment by JayBrown** [comment] 2016-03-14 11:33
I don't know what the problem was. I uninstalled a couple of tools, reset PRAM and SMC, and the Vienna 3.1.0 beta was suddenly working fine, so I expect 3.1.0 to work as well. If something happens in terms of crashing etc., I'll let you know of course. Thank you. It's the best RSS app for OS X by far.

**Comment by jimrome** [comment] 2016-03-14 14:29
This new version hangs on the attached situation. Repeatable.

James A. Rome
116 Claymore Lane
Oak Ridge, TN 37830-7674
865 482-5643
jamesrome@gmail.com
http://jamesrome.net

**Comment by jimrome** [comment] 2016-03-15 14:34
I now have 5.3GB on Vienna 3.1

James A. Rome
116 Claymore Lane
Oak Ridge, TN 37830-7674
865 482-5643
jamesrome@gmail.com
http://jamesrome.net

**Comment by barijaona** [comment] 2016-03-15 18:51
@jimrome apparently, you forgot the attachment announced in your message.

**Comment by jimrome** [comment] 2016-03-15 18:54
If I meant to attach, it was just the memory usage in Activity Monitor

James A. Rome
116 Claymore Lane
Oak Ridge, TN 37830-7674
865 482-5643
jamesrome@gmail.com
http://jamesrome.net

**Comment by josh64x2** [comment] 2016-03-15 19:50
@jimrome are you able to Export Subscriptions and send a copy? Perhaps one of your feeds is causing this issue and it would help in tracking it down.

THanks!

**Comment by jimrome** [comment] 2016-03-15 21:00
James A. Rome
116 Claymore Lane
Oak Ridge, TN 37830-7674
865 482-5643
jamesrome@gmail.com
http://jamesrome.net

**Comment by josh64x2** [comment] 2016-03-15 22:55
Got a copy of the opml file via email. Will import to a clean build of vienna for testing.

**Comment by josh64x2** [comment] 2016-03-15 22:58
I just re-read the bug report and noticed it also relates to #529

**Comment by barijaona** [comment] 2016-03-16 20:56
I don't have the OPML file, but I guess that @jmrome have a big database with numerous feeds and articles.

Vienna is aggressively caching articles in memory. So the memory may fill up relatively quickly.

Anyway, when I test by running the `memory_pressure` command, I notice that the OS quickly starts using compression in the memory allocated to Vienna. If the memory constraints continue to increase, Vienna will ultimately release its cache and will free up significant chunks of memory. Anyway, the machine remains responsive.

How is your own machine behaving when you apply `memory_pressure` ?

**Comment by jimrome** [comment] 2016-03-17 15:08
http://www.phonearena.com/news/Gather-round-First-LG-G5-photo-and-video-samples-are-up_id79332

This link hangs my vienna.

James A. Rome
116 Claymore Lane
Oak Ridge, TN 37830-7674
865 482-5643
jamesrome@gmail.com
http://jamesrome.net

**Comment by barijaona** [comment] 2016-06-04 19:03
I’ll close this, as there was considerable changes since first reports without additional clues.

**Closed by barijaona** 2016-06-04 19:03 UTC
Labels: bug
