### ISSUE TITLE
Vienna 3.1.0 on Mac OS X 10.11.3 and 10.11.4 crashing after sleep

### ISSUE THREAD

**Issue by Addicted2light** [ViennaRSS/vienna-rss#602] opened 2016-03-23 07:35 UTC
Vienna is crashing after the iMac (mid 2011, 24Gb ram, 2.7Ghz core i5) comes out of sleep, especially after long periods of sleep (for example in the morning).

This does not happen that frequently after short periods of sleep, like during the day when at most the computer will sleep a couple of hours or three.

Attached the log files from the crashes
[Archivio.zip](https://github.com/ViennaRSS/vienna-rss/files/185537/Archivio.zip)
. Thanks!

**Comment by barijaona** [comment] 2016-03-23 19:30
Duplicate of #590 . This one is solved in 3.1.1

**Closed** 2016-03-23 19:30 UTC
