### ISSUE TITLE
Empty article list for some feeds sometimes

### ISSUE THREAD

**Issue by MacDisein** [ViennaRSS/vienna-rss#599] opened 2016-03-22 09:47 UTC
With the latest version 3.1.1 :7cb6d42: on MacOSX 10.8.5 sometimes the article list for a feed is empty - but the badge indicates unread messages. I can show the articles in the list before unread messages arrived. If you wait for the next feed update and there are new unread messages sometimes the articles are visible again.
No filters set and a restart doesn't solve the problem.
![vienna_empty_article_list](https://cloud.githubusercontent.com/assets/8401876/13947531/76a04916-f01b-11e5-8bd0-b2e2ae69753a.jpg)

**Comment by josh64x2** [comment] 2016-03-22 09:50
This issue was also reported on the forums as well and I've copied some of the info to my fork https://github.com/josh64x2/vienna-rss/issues/23

**Comment by barijaona** [comment] 2016-03-25 02:27
Did you look at console log ? Might be exceptions in the article list view, and might be solved by commit 5e4097ef05e50ed6dd03a18269ac717c7b202ad8

**Comment by barijaona** [comment] 2016-03-26 15:22
Can you verify if it is fixed in 3.1.2 ?

**Comment by TigerHijinks** [comment] 2016-03-28 17:38
I'm still experiencing this issue.  Specifically affects xml feeds.  OSX 10.9.5 and Vienna 3.1.2.

Specific feeds I'm having issues with.

http://feeds.feedburner.com/RockPaperShotgun?format=xml
http://www.polygon.com/rss/index.xml
http://feeds.arstechnica.com/arstechnica/index?format=xml
http://www.huffingtonpost.com/feeds/verticals/science/blog.xml
http://www.huffingtonpost.com/feeds/verticals/technology/blog.xml

**Comment by MacDisein** [comment] 2016-03-29 09:12
In my configuration it seems to be okay now.

**Comment by barijaona** [comment] 2016-03-29 09:19
@TigerHijinks : could you please temporarily disable the "Check for new articles on startup" option, and when the issue reappears, quit the application and relaunch it, to verify if the issue persists ?

**Comment by MacDisein** [comment] 2016-03-29 12:56
It happened to me again today now.
Restart Vienna doesn't change anything - then I temporarily disabled the "Check for new articles on startup" option and restarted Vienna. Now all articles are visible for the suspect feed.
Then I enabled the option again and after restart Vienna the article list is empty for that feed.

**Comment by TigerHijinks** [comment] 2016-03-29 16:43
Yes, still occurring.  One slight difference, when the window first opens after a restart, I can view the articles in that folder. If I click away to another folder and then come back, the articles are no longer visible.
![screen shot 2016-03-29 at 9 40 12 am](https://cloud.githubusercontent.com/assets/18122573/14116002/92aa9482-f592-11e5-91cd-ed53829dc58b.png)

**Comment by barijaona** [comment] 2016-03-31 03:04
This is almost certainly related to the new caching mechanism. I am not able to reproduce this specific problem, but had solved similar ones in the past.
I have a few ideas, but I’d like to confirm : 
- if it affects especially feeds having a lot of articles or if it affects all feeds at once
- if the problem appears at startup or only after a refresh
- if you have noticed any case of the problem “solving itself”, just by letting the application opened and feeds periodically refreshed
- if quitting and relaunching the application (without refreshing) makes the articles reappear

**Comment by sorawee** [comment] 2016-03-31 04:55
I exported all subscriptions, moved `~/Library/Application Support/Vienna` to `~/Library/Application Support/Vienna.old` and imported the subscriptions again. However, the problem still persists.

**Comment by MacDisein** [comment] 2016-03-31 14:48
- Currently I have 10 feed subscribed - and only one is affected, this feed doesn't have a lot of articles (< 50).
- If I select the affected feed (article list is empty) and restart Vienna, articles are visible for a second only, then the list becomes empty
- Yes, during the day (keep Vienna opened) sometimes the articles are visible and sometimes not.
- If I start vienna with option 'Check for new articles on start up' unchecked the articles of the affected feed are visible - after the next refresh the articles are disappear.

**Comment by TigerHijinks** [comment] 2016-03-31 15:45
I have 5 affected feeds, listed above.  Unread articles as of this morning are 21, 8, 19, 1300, and 2353.  2 of the affected feeds are Feedburner XML style feeds, 3 are straight foobar.xml documents.  

With the option to check for new articles on startup disabled, when I start Vienna, I can see the articles the first time I select the folder.  If I select another folder and then go back to the first folder, I can no longer see the articles.  If I have a folder selected and manually refresh, usually I can no longer see the articles.  Occasionally, and I think it's when there is a new article fetched, I can still see articles after a manual refresh.  If the articles have disappeared, I can quit and restart and they are visible again, as long as I leave check for new articles on startup disabled.

For comparison purposes, my unaffected feeds are listed:

http://howardtayler.com/feed/
https://www.sparkfun.com/feeds/news
https://www.sparkfun.com/feeds/tutorials
https://blog.arduino.cc/feed/

**Comment by josh64x2** [comment] 2016-03-31 23:46
Could one of you please zip up `~/Library/Application Support/Vienna` and upload it here so I can try to reproduce?
I also noticed that one affected person is on 10.8.5 and @TigerHijinks is on 10.9.5. Is anyone on 10.10 or 10.11 and experiencing this issue?

Thanks!!

**Comment by MacDisein** [comment] 2016-04-01 07:37
[Vienna.zip](https://github.com/ViennaRSS/vienna-rss/files/199143/Vienna.zip)

**Comment by josh64x2** [comment] 2016-04-01 07:46
@MacDisein thanks! I can reproduce this on 10.8.5 so hopefully I can debug it.

**Comment by barijaona** [comment] 2016-04-02 17:30
@josh64x2 If you are able to reproduce problem on 10.8.5, can you test my branch [issue-599](https://github.com/barijaona/vienna-rss/tree/issue-599) ?

**Comment by josh64x2** [comment] 2016-04-02 22:45
@barijaona your branch seems to work :+1:

**Comment by barijaona** [comment] 2016-04-02 22:57
It is not completely finished yet. Would you please retest in a few minutes, after I submit other commits.

**Comment by barijaona** [comment] 2016-04-02 23:41
@josh64x2 can you retest now ?

**Comment by barijaona** [comment] 2016-04-02 23:48
I spoke too fast. Still some problems here.

**Comment by josh64x2** [comment] 2016-04-02 23:49
@barijaona what problems are you still having? The cache is staying on my 10.8.5 VM.

**Comment by barijaona** [comment] 2016-04-03 00:15
On 10.11, try this : 
1/ refresh all feeds
2/ go to one of the feeds with new articles ; you should see the new articles
3/ select another feed
4/ go back to the feed selected at step 2. In my tests, articles do not show anymore, because the `cachedGuids` array got empty

**Comment by josh64x2** [comment] 2016-04-03 00:38
I found some bad code:
`Database -(void)prepareCache:(NSCache *)cache forFolder:(NSInteger)folderId saveGuidsIn:(NSMutableArray *)cachedGuids`.
Database should not be accessing `Folder` instance variables. I think it should be refactored.

**Comment by barijaona** [comment] 2016-04-03 00:41
Yes, it's probably the culprit. If you have an idea, feel free to give it a try.
Here, it is 3:40 AM, I need a bit of rest :-)

**Comment by josh64x2** [comment] 2016-04-03 03:40
I suggest removing `NSCache` and reverting to 3.0.9 behaviour. There were no performance issues with 3.0.9 and `NSCache` has overhead when adding and retrieving objects. 
The code is too messy to be worth refactoring it :frowning:

**Comment by barijaona** [comment] 2016-04-03 07:45
From my point of view, 3.0.9 code is more weird.
I did the required refactoring and added some comments in the code : can you check it ?

**Comment by barijaona** [comment] 2016-04-04 05:03
Not sure that the problem is solved with recent PRs. Will investigate more.

**Comment by josh64x2** [comment] 2016-04-04 05:04
It appears solved to me on 10.8.5 testing, maybe build a development version and put it here for another 10.8 or 10.9 user to verify?

**Comment by barijaona** [comment] 2016-04-04 05:13
Some debugging code in [articlesWithFilter](https://github.com/ViennaRSS/vienna-rss/blob/master/src/Folder.m#L738-L752) to verify if the number of cached articles matches the number of elements from Database's `guidHistoryForFolderId:` might help understand better the source of the problem.

**Comment by barijaona** [comment] 2016-04-04 05:22
or an assertion comparing `self.unreadCount` and `self.cachedGuids.count`

**Comment by josh64x2** [comment] 2016-04-04 06:05
@barijaona even better than debugging code is this http://nshipster.com/new-years-2016/#beyond-breakpoints

I came across it the other day and it works very well :smile:

**Comment by barijaona** [comment] 2016-04-04 19:36
I encountered the problem of "invisible" articles with 10.11… Hopefully, I fully understand the origin of the issue now.

Could you please test the attached build which is based on my [issue-599](https://github.com/barijaona/vienna-rss/tree/issue-599) branch ?
[Vienna-test6c292a6.zip](https://github.com/ViennaRSS/vienna-rss/files/203179/Vienna-test6c292a6.zip)

**Comment by TigerHijinks** [comment] 2016-04-04 22:45
I get good results with that version.  Refresh works as does selecting different folders and coming back.

**Comment by MacDisein** [comment] 2016-04-05 13:30
The issue seems to be eliminated with the provided test version.

**Closed** 2016-04-06 09:04 UTC
Labels: bug
