### ISSUE TITLE
Gross problems in 3.8.0 : “Load Full HTML Articles” option is broken

### ISSUE THREAD

**Issue by macsrwe** [ViennaRSS/vienna-rss#1592] opened 2022-07-09 21:47 UTC
Got a message to upgrade to 3.8.0 this afternoon. After upgrading, clicking on postings in subscriptions results in no text in the text pane, for all but one of my subscriptions. (The only subscription that works properly anymore is xkcd.com.) The blue "unread" dot disappears on unread postings, but still no text appears.

**To Reproduce**
Steps to reproduce the behaviour, if possible.
I just upgraded. I did nothing else.

**Screenshots**
Add screenshots to help explain your problem, if possible.

**Please complete the following information:**
 - Vienna version 3.8.0
 - OS version: macOS 10.13.6

**Additional information:**
In which version of Vienna does the problem not occur, if applicable.
Whatever was the latest version available up until today. I intend to re-download and re-install that one shortly.

Note that all information available in the forum indicates that a previous version of Vienna is still the "preferred version." 
Any information there about 3.8.0 is not at all obvious.

![image](https://user-images.githubusercontent.com/14959147/178123629-5689b287-fb69-4264-a3d1-e0663427ccd8.jpeg)

**Comment by macsrwe** [comment] 2022-07-09 22:02
I have not used a beta. I am not using an experimental browser. I changed no settings at all, I just launched Vienna and tried to read postings. No postings appear in the text pane.

I just replaced 3.8.0 with 3.7.4 again and the problem disappeared.

**Comment by macsrwe** [comment] 2022-07-09 22:18
Maybe it depends on my preferences. Here's what I have. Note: I cannot make Vienna 3.7.4 select any default RSS reader other than Vienna.8.0.app (it ignores my choice of the 3.7.4 Vienna.app), but it shouldn't matter.
![image](https://user-images.githubusercontent.com/14959147/178124312-3f739b05-806e-4c24-9661-817c8540d113.jpeg)
![image](https://user-images.githubusercontent.com/14959147/178124354-749ecdf6-1e88-4289-98a0-e4e7867a7cbe.jpeg)
![image](https://user-images.githubusercontent.com/14959147/178124322-dc34653e-2e4b-4bfd-85f0-0af0a96bc759.jpeg)
![image](https://user-images.githubusercontent.com/14959147/178124327-861a338e-0d2f-4e3f-8905-56e481ea0040.jpeg)
![image](https://user-images.githubusercontent.com/14959147/178124330-7246679e-5aab-4f5d-9343-49c71593ce03.jpeg)

**Comment by josh64x2** [comment] 2022-07-10 00:04
I can also reproduce this issue.

**Comment by barijaona** [comment] 2022-07-10 05:20
I set release appcast to use 3.7.4, beta and release candidate to use 3.8.0

**Comment by barijaona** [comment] 2022-07-10 05:51
I have:
- set 3.7.4 to be displayed as most recent release on Github, Sourceforge and vienna-rss.com
- submitted a pull request to homebrew https://github.com/Homebrew/homebrew-cask/pull/127511

**Comment by josh64x2** [comment] 2022-07-11 23:06
Closed via PR #1594

**Closed by josh64x2** 2022-07-11 23:06 UTC
Labels: bug :lady_beetle:, critical :warning:

**Comment by landy2005** [comment] 2022-07-13 16:15
But can you release this fix into main channel?
Since latest "stable" version is unusable..

**Comment by barijaona** [comment] 2022-07-14 02:41
> But can you release this fix into main channel?
> 
> Since latest "stable" version is unusable..

Please re-download and install manually the version currently tagged stable (3.7.4). 
Sorry for the inconvenience. 

There are a few other issues that we will work on before releasing 3.8.1

**Comment by josh64x2** [comment] 2022-07-14 04:47
@barijaona Is there a way to tell Sparkle to only update to v3.8.1 for people who got auto-updated to v3.8.0? I think it would be good to release the fix for this major issue whilst we work on some of the other smaller issues for 3.8.2...
