### ISSUE TITLE
Feed subfolders disappeared and content feeds move to the main feed list

### ISSUE THREAD

**Issue by carpecrustum** [ViennaRSS/vienna-rss#1784] opened 2024-07-29 01:58 UTC
All but two feed folders have disappeared. The feeds that were in those folders still exist, they're at the main level of the feed list now. They're not sorted in any particular order or next to the other feeds that had shared the same folder. They occur randomly throughout the main list.

I don't know what I did to cause this. The only thing that I've done in the past few days is to accidentally add a new folder inside another folder. I put the new feeds that I was adding into it and then I dragged it out of the wrong folder, putting it right below.

Today, I noticed that all of my previous folders that were below the new one have disappeared. 
As I said, I don't have steps to reproduce this, but I'm curious to see if anyone else reports the same issue.

I'm using Vienna Version 3.9.1 :a82691eb: (8219)
on MacOS 13.0 ( Ventura )

**Comment by barijaona** [comment] 2024-07-29 04:29
This is the same issue as #1768, so I will close this one. Thanks for the details though. 
I am currently working on this issue (pull request #1783).

**Comment by carpecrustum** [comment] 2024-07-29 04:44
It seems that my missing group folders are just invisible. I tried to recreate two of them using the original names and nothing happens, but I can create and see new group folders if they have names that I didn't use before.

**Comment by barijaona** [comment] 2024-07-29 07:00
Thanks for this !

**Comment by barijaona** [comment] 2024-08-15 18:38
I am closing this here ; you are welcome to open a new issue if a similar problem occurs with Vienna 3.9.2 or later.

If you have any issue caused by 3.9.1, switch temporarily to (alphabetical) auto sort and all folders should get back.

**Closed by barijaona** 2024-08-15 18:38 UTC
