### ISSUE TITLE
InoReader Authentication Failed

### ISSUE THREAD

**Issue by aint** [ViennaRSS/vienna-rss#1293] opened 2020-02-09 13:51 UTC
Hi there,

I'm experiencing some authentication issue with InoReader. It started a couple days ago or something. I didn't change my password and Android InoReader app works perfectly well, so I'm assuming that there is an issue with Vienna.
Also, I noticed that InoReader introduced some [updates](https://blog.inoreader.com/2020/01/inoreader-v13-is-here-with-improved-looks-and-new-features.html) recently. 

![image](https://user-images.githubusercontent.com/3179252/74103228-25658380-4b53-11ea-9cfe-c7ae49581135.png)

**Comment by josh64x2** [comment] 2020-02-09 20:09
Duplicate of #1252

**Closed by josh64x2** 2020-02-09 20:09 UTC
