### ISSUE TITLE
emojis in title break line height

### ISSUE THREAD

**Issue by Tafkas** [ViennaRSS/vienna-rss#1097] opened 2018-03-11 17:17 UTC
If the rss feed item's title contains an emoji the line height is not displayed properly.

See screenshot ![](https://i.imgur.com/XH8ybLc.png)

**Comment by DavidMunch** [comment] 2018-03-12 07:15
Related to #447.

**Comment by barijaona** [comment] 2018-03-14 05:38
I'll close it as a duplicate of #447

**Closed by barijaona** 2018-03-14 05:38 UTC
