### ISSUE TITLE
Date and Author Pushed Away for Titles or Authors with Non-English Characters

### ISSUE THREAD

**Issue by FakeYin** [ViennaRSS/vienna-rss#537] opened 2015-11-15 19:46 UTC
Issues appeared in El Capitan as shown in the image.
![screen shot 2015-11-16 at 03 46 38](https://cloud.githubusercontent.com/assets/15860714/11170616/abe8e3e6-8c14-11e5-93a1-39a16330fe4b.png)

**Comment by FakeYin** [comment] 2015-11-15 19:54
This may be the same issue as Issue #516.

**Comment by FakeYin** [comment] 2015-11-15 22:56
The font may be responsible for the issue.  
e.g., Klee 
![screen shot 2015-11-16 at 06 52 25](https://cloud.githubusercontent.com/assets/15860714/11171587/ec525bf0-8c2e-11e5-9c07-4886dc962674.png)

e.g., PingFang HK
![screen shot 2015-11-16 at 06 55 47](https://cloud.githubusercontent.com/assets/15860714/11171593/162f88f8-8c2f-11e5-8627-64c4ae409f66.png)

**Comment by barijaona** [comment] 2016-11-27 22:45
Duplicate of #447

**Closed by barijaona** 2016-11-27 22:45 UTC
