### ISSUE TITLE
Enclosed image don't scale correctly

### ISSUE THREAD

**Issue by rmens** [ViennaRSS/vienna-rss#669] opened 2016-06-06 09:49 UTC
When resizing the window, enclosed images should keep their aspect ratio.

![schermafbeelding 2016-06-06 om 11 48 48](https://cloud.githubusercontent.com/assets/6742496/15818263/b5ace432-2bdc-11e6-9a70-e5016e4ac30e.png)
![schermafbeelding 2016-06-06 om 11 48 51](https://cloud.githubusercontent.com/assets/6742496/15818264/b7509ae0-2bdc-11e6-9ada-d9589f290446.png)

**Comment by marchyman** [comment] 2016-06-06 18:23
On Jun 6, 2016, at 2:49 AM, Raymon Mens <notifications@github.com> wrote:
> 
> When resizing the window, enclosed images should keep their aspect ratio.

I reported something very similar quite a while ago.  That issue was closed as it only seemed to happen to me.  In my case it was with articles containing an image that was larger in at least one one dimension than my current window size.  Example: this article from boing boing

http://feeds.boingboing.net/~r/boingboing/iBag/~3/E05FjouO2ZU/david-byrne-wants-you-to-regis.html

contains a 1032 x 656 image.   When I look at the article in Vienna I see an image compressed in the X dimension to fit my window width and for some reason slightly extended in the Y direction.

I use horizontal layout with FeedLight Graphite style.

Marc

**Comment by rmens** [comment] 2016-06-06 21:24
It's not you. Actually it was reported by one of the readers of the website i'm writing for and i was able to reproduce this.

**Comment by josh64x2** [comment] 2016-06-06 23:29
I've confirmed this issue still exists

**Comment by barijaona** [comment] 2016-06-07 04:36
I could not reproduce this.
It’s probably an HTML/CSS issue. Can you have a look at the templates ? They are in the `SharedSupport/Styles folder`. These .viennastyle objects are packages : control-click to show their contents.
Also, check that you have no personal styles in the `~/Library/Application Support/Vienna/Styles` folder, because they will prevail over those built in app.

**Comment by josh64x2** [comment] 2016-06-07 04:37
@barijaona I'm getting this with the "Default" style. It definitely affects boingboing.net so maybe they are doing something weird with their `<img>` tags ?

**Comment by barijaona** [comment] 2016-06-07 04:49
yeah, probably related to the `sizes` attribute

**Comment by marchyman** [comment] 2016-06-07 05:11
Just added that to /Applications/Vienna.app/Contents/SharedSupport/Styles/FeedLight Graphite.viennastyle/stylesheet.css.  It seems to do the trick.  Thanks.

**Comment by josh64x2** [comment] 2016-06-07 05:12
OK we should add this to all of the stylesheets then.

**Comment by josh64x2** [comment] 2016-06-08 02:13
fixed in pr #668

**Closed by josh64x2** 2016-06-08 02:13 UTC
Labels: bug
