### ISSUE TITLE
V3.1 crashing regularly

### ISSUE THREAD

**Issue by hopkinsje** [ViennaRSS/vienna-rss#590] opened 2016-03-17 10:35 UTC
The current (3/17, 6:30am) release version crashes on my iMac Retina (27-in, late 2015)running OSX v10.11.3. Unfortunately I can't identify any triggers for the crashes, other than that the program has always been running for a period of time (10 minutes to an hour or longer) and isn't being used at the time of the crash. Have reverted to 3.09, which is stable on my machine.

**Comment by barijaona** [comment] 2016-03-17 17:43
Can you send some .crash files ? They are in ~/Logs/DiagnosticsReports

**Comment by hopkinsje** [comment] 2016-03-17 17:46
Sure — three attached.

**Comment by barijaona** [comment] 2016-03-17 17:49
Attachments not received. Please, post them through the web interface, rather than by replying to mail.

**Comment by hopkinsje** [comment] 2016-03-18 11:26
Here you go. 
[Archive.zip](https://github.com/ViennaRSS/vienna-rss/files/179533/Archive.zip)

**Comment by phiw13** [comment] 2016-03-18 12:33
@hopkinsje

Do you use smart folders in Vienna (e.g. “Today”)?
When the crash happens is the (a) smart folder selected?

I’ve seen occasional crashes similar to you under these conditions: a smart folder “all unread” is selected when Vienna refreshes – and – that smart folder contains flagged, unread articles. I certainly *cannot* reproduce the crash on demand.

**Comment by hopkinsje** [comment] 2016-03-18 13:08
Thanks for checking out the issue. I do use smart folders — I leave V. open, with Unread Articles selected. I can use workarounds (using the old version, which isn’t a great plan; or opening and closing it when I need it), but that’s not real handy.

I’m no programmer, but the problem feels similar to others I’ve seen that turned out to be related to memory leaks. Perhaps a memory leak when a smart folder is left selected? 

I’ll spend a little time trying to trigger the issue, but some time needs to pass before V. crashes, which makes it tough to trigger on demand. Whatever, I know 3.1 is different, at least for me, than 3.09. I’ve had 3.09 open for days now with no issues.

Jim

**Comment by barijaona** [comment] 2016-03-18 22:12
From the crash logs sent by @hopkinsje, it appears that the use of a NSPasteboard for the `+stringByCleaningURLString:` method in `StringExtensions.m` is not thread safe.

I will modify this method.

**Comment by barijaona** [comment] 2016-03-19 10:08
@hopkinsje can you verify if the 3.1.1 version is more stable for you ?

**Comment by hopkinsje** [comment] 2016-03-19 11:14
Will be home in 15 min and will load it then.

**Comment by hopkinsje** [comment] 2016-03-19 12:04
Just crashed again — running for less than an hour. Will post the log.

J

**Comment by hopkinsje** [comment] 2016-03-19 12:08
Log from v1.1 crash
[Vienna_2016-03-19-080335_Jims-IMac-5K-2015.crash.zip](https://github.com/ViennaRSS/vienna-rss/files/180799/Vienna_2016-03-19-080335_Jims-IMac-5K-2015.crash.zip)

**Comment by barijaona** [comment] 2016-03-22 17:39
Could you test the attached version ? (7.5 Mb)

[Vienna-commit784944c.app.zip](https://github.com/ViennaRSS/vienna-rss/files/184640/Vienna-commit784944c.app.zip)

**Comment by hopkinsje** [comment] 2016-03-22 17:45
Sure. Just loaded it and will let you know. Shouldn’t take too long to see
if stability has improved.

**Comment by phiw13** [comment] 2016-03-23 04:35
Arg, just got hit by this crash (first time in quite a longish while): the selected folder was a smart folder (‘all unread’) which contains all unread articles, some of them are flagged. I was arrowing down through the list (some articles become “read”), then Vienna refreshed — at that point the list contains both read and unread articles as the list is only refreshed after changing views.I think Vienna crashed the moment some new articles got added to the list (very low traffic this time of the day, only a low few new articles added every hour).

I will now try the build linked above.

**Comment by hopkinsje** [comment] 2016-03-23 09:31
Sorry, still having the issue — crashed overnight. I’ll post the log to
GitHub.

Jim

**Comment by hopkinsje** [comment] 2016-03-23 09:33
The test version "Vienna 3" ran longer this time, but crashed at about 5:30 this morning. Log attached.
[Vienna_2016-03-22-211351_Jims-IMac-5K-2015.crash.zip](https://github.com/ViennaRSS/vienna-rss/files/185696/Vienna_2016-03-22-211351_Jims-IMac-5K-2015.crash.zip)

**Comment by barijaona** [comment] 2016-03-26 15:24
@hopkinsje can you confirm if it is fixed in 3.1.2 ?

**Closed by barijaona** 2016-03-26 15:24 UTC
Labels: bug, ready

**Comment by hopkinsje** [comment] 2016-03-26 15:48
Sure. Will load it and give it a run.


J

**Comment by hopkinsje** [comment] 2016-03-26 16:46
Per the above, was evaluating Version 3.1.2 :86bfc3d to see if the crashing I'd experienced was fixed and noticed a new problem. When new posts show up, the badge counter shows the number of new posts, as expected. However, if I then go into Vienna to see the posts, Vienna is frozen. The new messages don't appear in the "Unread Articles" folder and I'm unable to do anything but quit the app. If I quite and return to it, I can view the new messages and the program operates as expected.

**Comment by barijaona** [comment] 2016-03-26 21:50
I think this is unrelated to the initial problem.
Selecting smart folders / group folders or updating their display after a refresh can be very CPU intensive because these operations require execution of SQL code.
The problem is that this is done on the main thread, so the application may become unresponsive for a long time, especially with large database.
Changing this will require more code refactoring, and we are hesitating between improving the current code base and restarting from a completely new design.

**Comment by hopkinsje** [comment] 2016-03-26 22:18
Got it. I've never experienced the "freeze" with v3.09, which is why I reported it, but the problem happens  every time with the latest version. For reference, I have about 80 sites that I track in the app. 

Jim

**Comment by barijaona** [comment] 2016-03-26 23:31
The problem might be aggravated with Open Reader feeds and the 3.1 version, because there are successive notifications to refresh the display while the process is still running. I will try to have a look at it.

**Comment by hopkinsje** [comment] 2016-03-26 23:38
Thanks.

J
