### ISSUE TITLE
Strange view pane shown while importing/exporting RSS subscriptions

### ISSUE THREAD

**Issue by walterdolce** [ViennaRSS/vienna-rss#713] opened 2016-10-02 12:08 UTC
Hi all, this started happening all of a sudden. Note the various panes at the bottom of the dialog. Please see screenshot.

<img width="714" alt="screen shot 2016-10-02 at 13 02 09" src="https://cloud.githubusercontent.com/assets/6195629/19020450/189b63cc-88a1-11e6-9c83-eaa07929bd36.png">

FWIW, I upgraded to Sierra a couple of days ago but I can't tell whether this happened before or after the OS upgrade.

Thanks!

**Comment by barijaona** [comment] 2016-10-31 21:39
Can you check if version 3.1.6 improves things ?

**Comment by walterdolce** [comment] 2016-11-01 08:25
I already have 3.1.6 :)

**Comment by barijaona** [comment] 2016-11-01 17:35
So, can you confirm if the problem is solved ?

**Comment by walterdolce** [comment] 2016-11-01 20:23
The problem is not solved.

**Comment by josh64x2** [comment] 2016-11-01 20:29
Can you please take a screenshot of the About Vienna window so I can make sure I'm running the same version as you?

**Comment by walterdolce** [comment] 2016-11-02 10:45
Sure! Here it is:

<img width="298" alt="screen shot 2016-11-02 at 10 43 37" src="https://cloud.githubusercontent.com/assets/6195629/19925796/62afe5fe-a0e9-11e6-9632-922bbb4f0e30.png">

I noticed the issue above doesn't *always* happen. It's inconsistent it seems. 
Let me know what I can do to help debugging this.

**Comment by josh64x2** [comment] 2016-11-27 23:13
This was fixed with PR #718

**Closed by josh64x2** 2016-11-27 23:13 UTC
