### ISSUE TITLE
Hangs when deleting feed

### ISSUE THREAD

**Issue by mankoff** [ViennaRSS/vienna-rss#404] opened 2014-12-11 11:47 UTC
If I delete a feed, the UI appears to partially hang. I delete it by two-finger-tapping (CTRL+tap) on the feed name and then selecting "delete" from the popup menu. I am asked to confirm and do so. Then nothing happens. The feed is still listed in the sidebar, but Vienna is not responsive. If I quit and restart, the feed is gone.

A compounding issue with this bug is that CTRL+click still brings up the popup menu even though the app is hung. I can select "Delete" again. Since the feed still appears in the sidebar, this is a natural sequence of events. But the feed actually has been deleted, even though it is still listed, and this second attempt to delete it actually deletes other feeds instead.

**Comment by loveencounterflow** [comment] 2015-11-12 20:36
I can totally confirm this. Basically, you can only ever delete one feed at a time, then you have to quit the app with the help of Activity Monitor's 'force quit', and restart.

**Comment by wmangano** [comment] 2016-02-16 01:25
confirmed

only way out ... force quit. pretty annoying bug

**Comment by wmangano** [comment] 2016-02-17 23:17
bug still exists in 3.1.0 beta 5. i can still enter application menues but whole ui becomes unresponsive.

"force quit" helps

**Comment by josh64x2** [comment] 2016-02-18 23:45
I still can't reproduce this. @wmangano are you able to send a copy of your entire `~/Library/Application Support/Vienna/` folder?

**Comment by wmangano** [comment] 2016-02-18 23:56
Its about 1,8GB in size

**Comment by josh64x2** [comment] 2016-02-18 23:58
I am OK with downloading that much data - are you not able to send it?

**Comment by wmangano** [comment] 2016-02-19 00:08
Sorry nope.

But i hope this one might help:

I started Vienna via cmdline...deleted one feed and received this error message in console.

`2016-02-19 01:06:19.540 Vienna[86425:3727604] NSConcreteMutableAttributedString initWithString:attributes:: nil value
2016-02-19 01:06:19.563 Vienna[86425:3727604] (
	0   CoreFoundation                      0x00007fff848e4ae2 __exceptionPreprocess + 178
	1   libobjc.A.dylib                     0x00007fff932d5f7e objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff848e498d +[NSException raise:format:] + 205
	3   Foundation                          0x00007fff927a79f8 -[NSConcreteMutableAttributedString initWithString:attributes:] + 140
	4   Vienna                              0x000000010f465fae Vienna + 352174
	5   AppKit                              0x00007fff86dd0b41 -[NSTableView preparedCellAtColumn:row:] + 424
	6   AppKit                              0x00007fff86dd084c -[NSTableView _drawContentsAtRow:column:withCellFrame:] + 50
	7   AppKit                              0x00007fff86dd0409 -[NSTableView drawRow:clipRect:] + 1678
	8   AppKit                              0x00007fff86dcfaeb -[NSTableView drawRowIndexes:clipRect:] + 919
	9   AppKit                              0x00007fff86dce403 -[NSTableView drawRect:] + 1480
	10  AppKit                              0x00007fff86c671fe -[NSView(NSInternal) _recursive:displayRectIgnoringOpacity:inGraphicsContext:CGContext:topView:shouldChangeFontReferenceColor:] + 1331
	11  AppKit                              0x00007fff86c66b98 __46-[NSView(NSLayerKitGlue) drawLayer:inContext:]_block_invoke + 242
	12  AppKit                              0x00007fff86c66843 -[NSView(NSLayerKitGlue) _drawViewBackingLayer:inContext:drawingHandler:] + 2403
	13  AppKit                              0x00007fff86c65ed5 -[NSView(NSLayerKitGlue) drawLayer:inContext:] + 108
	14  QuartzCore                          0x00007fff8a301e79 CABackingStoreUpdate_ + 3494
	15  QuartzCore                          0x00007fff8a3010cd ___ZN2CA5Layer8display_Ev_block_invoke + 59
	16  QuartzCore                          0x00007fff8a2f4d31 _ZN2CA5Layer8display_Ev + 1565
	17  AppKit                              0x00007fff86bd907c _NSBackingLayerDisplay + 641
	18  AppKit                              0x00007fff86bd67bd -[_NSViewBackingLayer display] + 818
	19  QuartzCore                          0x00007fff8a2f310d _ZN2CA5Layer17display_if_neededEPNS_11TransactionE + 603
	20  QuartzCore                          0x00007fff8a2f278d _ZN2CA5Layer28layout_and_display_if_neededEPNS_11TransactionE + 35
	21  QuartzCore                          0x00007fff8a2f1cf1 _ZN2CA7Context18commit_transactionEPNS_11TransactionE + 277
	22  QuartzCore                          0x00007fff8a2f1a24 _ZN2CA11Transaction6commitEv + 508
	23  QuartzCore                          0x00007fff8a300917 _ZN2CA11Transaction17observer_callbackEP19__CFRunLoopObservermPv + 71
	24  CoreFoundation                      0x00007fff847f3e37 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
	25  CoreFoundation                      0x00007fff847f3da7 __CFRunLoopDoObservers + 391
	26  CoreFoundation                      0x00007fff847e5358 CFRunLoopRunSpecific + 328
	27  HIToolbox                           0x00007fff8e3a0935 RunCurrentEventLoopInMode + 235
	28  HIToolbox                           0x00007fff8e3a0677 ReceiveNextEventCommon + 184
	29  HIToolbox                           0x00007fff8e3a05af _BlockUntilNextEventMatchingListInModeWithFilter + 71
	30  AppKit                              0x00007fff86c030ee _DPSNextEvent + 1067
	31  AppKit                              0x00007fff86fcf943 -[NSApplication _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 454
	32  AppKit                              0x00007fff86bf8fc8 -[NSApplication run] + 682
	33  AppKit                              0x00007fff86b7b520 NSApplicationMain + 1176
	34  libdyld.dylib                       0x00007fff8f59c5ad start + 1
)`

**Comment by josh64x2** [comment] 2016-02-19 00:10
OK thanks. Do you know the link to the feed you deleted? Maybe there is something odd about the feed when it is saved in the Vienna database which is causing these issues.

**Comment by wmangano** [comment] 2016-02-19 00:11
https://guides.github.com/feed/index.xml

**Comment by josh64x2** [comment] 2016-02-19 00:12
Hrm no issues here deleting it. I will investigate this weekend and create a test build for you to try with a fix.

**Comment by wmangano** [comment] 2016-02-19 00:12
give it a try....but i dont think that it had something to do with the feed ... since it happens with every feed

**Comment by wmangano** [comment] 2016-02-19 00:19
is it possible to attach a screenshot?

i think its a problem in the gui ... i can see in console that i can still update feeds in vienna....but the vienna gui itself stuck/does not update view

**Comment by wmangano** [comment] 2016-02-19 00:34
![vienna_screenshot](https://cloud.githubusercontent.com/assets/15934260/13162892/86219b4c-d6a8-11e5-9cc4-730a77e16f76.jpg)

**Comment by wmangano** [comment] 2016-02-19 00:46
another screenshot.

you can see in top left corner that im still able to open/browse through top menu ... but the feed column is empty (white) and i cannot confirm the "deletion dialog" ... whole ui is unresponsive

![vienna_screenshot2](https://cloud.githubusercontent.com/assets/15934260/13163099/6f17e558-d6aa-11e5-8f5d-c31e9d9e8935.jpg)

**Comment by barijaona** [comment] 2019-01-21 06:01
Closing this, as I could not reproduce, and no recent news about it.

**Closed by barijaona** 2019-01-21 06:01 UTC
Labels: bug :bug:
