### ISSUE TITLE
Open Reader Authentication Failed with InoReader

### ISSUE THREAD

**Issue by EricG-Personal** [ViennaRSS/vienna-rss#1298] opened 2020-04-08 13:29 UTC
I am using Vienna with my InoReader account, but the sync stopped working with an authentication failure. I can go to www.inoreader.com and log into my account without issue using my username and password.

I am using Version 3.5.5 :817110fe: (7130) on macOS 10.15.4 (Catalina).

**Comment by josh64x2** [comment] 2020-04-08 20:33
Duplicate of #1252

**Closed** 2020-04-08 20:33 UTC
