### ISSUE TITLE
Unusual hits in the Open RSS service

### ISSUE THREAD

**Issue by ansani** [ViennaRSS/vienna-rss#1733] opened 2024-01-28 20:12 UTC
Hi!
I just received an email from Mark of Open RSS service:

"Vienna RSS reader is hitting our server very frequently and isn’t respecting our Cache-Control​ headers. The requests are actually coming in all at the same time, similar to a DDoS attack.

We were about to just block the Vienna reader as it’s causing a pretty big strain on our servers."

I will try to investigate the issue of the headers' handling.

**Comment by josh64x2** [comment] 2024-01-29 00:10
Thank you for this report, we will take a look at it again. Please let me know the results of your investigation.

**Comment by TAKeanice** [comment] 2024-07-20 12:20
https://github.com/ViennaRSS/vienna-rss/releases/tag/v%2F3.9.1 contains a fix for this issue. @ansani could you confirm that the issue is fixed? I will close it for now, if there is still an issue let us know.

**Closed by TAKeanice** 2024-07-20 12:20 UTC
Labels: OpenReader :cloud:
