### ISSUE TITLE
Can no longer sort article subscriptions at all

### ISSUE THREAD

**Issue by PacoH** [ViennaRSS/vienna-rss#1734] opened 2024-01-29 16:16 UTC
Version 3.9.0. OS X Ventura 13.6.3

I used to have all my subscriptions sorted by my own preferences with most used ones on top. I pruned many unused ones and exported what remained before updating the app. When I imported the saved export, all subscriptions were/are sorted alphabetically, which is something I would never want. Worse, when I try to move one of them, it jumps back to its original position, something it never did before. I see no setting that allows a choice of sort order. Either a bug or some setting I am missing.

**Comment by PacoH** [comment] 2024-01-30 22:20
Thanks!

Hah hah hah. That's it! I was only checking general Settings. I probably had that checked in the previous version (Vienna 3.7.4). I checked and I did. I exported all the folders from that version and re-imported them, deleting the previous ones first. Now they are all in the original order I had them in. One thing though. All articles are marked unread now.

Is there a way I can reuse the original data in the update now without importing it so I can preserve the play status? Probably not because I just updated from within the old version and all articles are now shown as unread. I think this would require a new feature.

**Comment by carpecrustum** [comment] 2024-03-22 15:57
I have been having the same problem. The suggestion to set "Order By" to 'manual' only partially works for me.
Vienna randomly resets "Order By" to 'name' and I have to switch back to manual and then drag my feed folders back into the order that I had them in. 
This is the second time this week that I've had to restore my preferred order.

**Comment by PacoH** [comment] 2024-03-22 16:47
I have this same problem, especially after an update.

**Comment by carpecrustum** [comment] 2024-03-22 18:22
That might be part of my problem, I had 'check for newer versions of Vienna on start up' checked. 
I assumed it would just notify me when there were updates available. If it's automatically installing the updates rather than letting me know when one is available, then that could be the cause of my resets. 
I've unchecked it, maybe my manual ordering will stay selected now.

**Comment by PacoH** [comment] 2024-03-22 21:20
I set it for 'Check for newer versions of Vienna on start up' and I think it might be automatically installing the updates too. You know what's even worse? It marks all episodes as 'unread', which defeats the purpose of an aggregator. Time for two bug reports.

**Comment by carpecrustum** [comment] 2024-04-03 02:26
It has alphabetized everything again, disregarding the custom organization that I had done - even though "Check for newer versions" was unchecked. 
I'm out of ideas.

**Comment by barijaona** [comment] 2024-07-10 11:58
There is work in version 3.9.1 related to this issue. Can you confirm / infirm if there is an improvement?

**Comment by carpecrustum** [comment] 2024-07-10 13:51
I've never figured out what was the trigger for the alphabetizing of the folders, so I just prefixed my folders with "1 -", "2 -", etc. in the order that I wanted them.
I'll take the prefixes off the folder names but I won't be able to give you an immediate confirmation that it's better. 
All I can do is add another comment when/if it happens again.

**Comment by barijaona** [comment] 2024-07-12 04:35
Closing this as #1768 is more up to date.

**Closed by barijaona** 2024-07-12 04:35 UTC
Labels: bug :lady_beetle:
