### ISSUE TITLE
Hide "Search for folders" search box

### ISSUE THREAD

**Issue by TuomLarsen** [ViennaRSS/vienna-rss#787] opened 2017-02-21 12:20 UTC
I recently upgraded to Vienna 3.1.8 and now it shows  "Search for folders" search box in the very top left corner.

Is it possible to hide it, like it was in previous versions (it there was one, at all, that is...)?

**Comment by josh64x2** [comment] 2017-02-23 07:53
Hi @TuomLarsen, this will be coming in Vienna 3.2.x - keep an eye out 👍

**Comment by josh64x2** [comment] 2017-02-23 07:55
Duplicate of #582

**Closed by josh64x2** 2017-02-23 07:55 UTC
