### ISSUE TITLE
Vienna 3.9.1 changes article sort order after MacOS update reboot.

### ISSUE THREAD

**Issue by liamgreenwood** [ViennaRSS/vienna-rss#1768] opened 2024-07-11 01:08 UTC
**Describe the bug**
Rebooted my system as part of an update to 14.6, Vienna started with subscriptions in the wrong order. This is *NOT* a reoccurance of the View->Order By setting bug (that's fixed, thank you)

**To Reproduce**
Happens after some reboots.

**Screenshots**
I have an opml file with the correct order, and I have an opml file with the changed order after reboot.  Please let ma know how to send them to you.

**Please complete the following information:**
 - Vienna version 3.9.1
 - OS version: 14.6

**Comment by barijaona** [comment] 2024-07-11 07:12
barijaona at gmail dot com

**Comment by barijaona** [comment] 2024-07-12 04:30
Thanks for the data you sent me.
Obviously, the root cause of this problem is the same than the one which caused brutal changes in the "View->Order By" setting (issues #1732, #1734 and #1743).

Vienna 3.9.1 implements a better workaround than 3.9.0 when an internal inconsistency occurs (between the folders tree view and the database), but the root cause remains unknown.
But thanks to the sample you provided, I now have a clue.

**Comment by barijaona** [comment] 2024-07-12 04:32
Closing this as #1768 is more relevant now.

**Comment by barijaona** [comment] 2024-07-13 09:05
@liamgreenwood : I guess you are quite active on updating your feed list ?
can you give this build a test run ?

[ViennafoldersTree.tgz](https://github.com/user-attachments/files/16201500/ViennafoldersTree.tgz)

**Comment by barijaona** [comment] 2024-07-21 19:50
@liamgreenwood I updated my foldersTree branch.

Can you test this build ?

[ViennafoldersTree2.tgz](https://github.com/user-attachments/files/16325845/ViennafoldersTree2.tgz)

**Comment by barijaona** [comment] 2024-07-22 22:45
I am wondering if this issue might be related to a database problem. Would you please run these two commands in Terminal, and report the output ?

```
cd ~/Library/Application\ Support/Vienna
sqlite3 messages.db "PRAGMA integrity_check" 
```

**Comment by StariusPrime** [comment] 2024-08-15 12:20
I updated to 14.6 today and now all my folders (save for one) have disappeared and I can't create new ones. 
Coming here now, I see that "its a thing."

**Comment by barijaona** [comment] 2024-08-15 14:19
Switch temporarily to (alphabetical) auto sort and all folders should get back.
I will release 3.9.2 in a few hours, which should be much more stable on this.

**Comment by StariusPrime** [comment] 2024-08-15 17:24
> Switch temporarily to (alphabetical) auto sort and all folders should get back. I will release 3.9.2 in a few hours, which should be much more stable on this.

Thank you for the update!  It seems to have returned my folder structure!  👍  Much appreciated.  
I'm sorry it took a problem like this for me to even make a presence over here, but I wanted to say that I have been using Vienna for years and it's always been just what I wanted in a RSS reader.  So thank you very much!

**Comment by barijaona** [comment] 2024-08-15 18:34
I am closing this ; you are welcome to open a new issue if a similar problem occurs with Vienna 3.9.2 or later.

**Closed by barijaona** 2024-08-15 18:34 UTC
