### ISSUE TITLE
Vienna RSS should never ever implicitly modify feed URL for HTTP 301 responses

### ISSUE THREAD

**Issue by xaka** [ViennaRSS/vienna-rss#380] opened 2014-11-06 02:30 UTC
The long story short - I've just lost my entire RSS database because of that implicit behavior and I have no idea how to restore it. I was at Cisco office and they have weird network rules so for all HTTP requests they do transparent proxying and send HTTP 301 as a response code. In a matter of seconds after I turned on my WiFI I've lost everything. All feed URLs look the same now with internal Cisco domain names, etc. If there is HTTP 301, you're better to ask for confirmation first. I'm sorry, but I'm really upset now, but I still like the project.

https://github.com/ViennaRSS/vienna-rss/blob/d46d3143b245353adde8695fda467e9dad7a1af4/src/RefreshManager.m#L624

**Comment by josh64x2** [comment] 2015-01-26 01:18
@xaka what do you think about having something in the preferences? e.g. "Ignore permanent redirects - useful for those who use wifi hotspots in hotels etc"

**Comment by josh64x2** [comment] 2015-01-26 01:46
Another approach:

As Vienna, when I start refreshing feeds:

1. I refresh a feed and get a 301 status code
2. I prompt the user with the following options:
 * Update this feed's location
 * Do not update this feed's location
 * Do not update ANY feeds in this session
 * Never update feeds (this could be the same as triggering the preferences option in my previous comment

cc @barijaona

**Comment by xaka** [comment] 2015-01-26 05:27
@josh64x2 Having an option in preferences is always a good idea as it improves overall flexibility. What I'm not sure about is enabling redirects by default as that's exactly what happened in my case without my knowledge or expectation. The damage it does would make bigger impact on a user than bug him/her with a message about subscription, which has been moved to different location and solution could be as simple as confirmation dialog with new URL and Apply/Cancel buttons. Such dialog would appear to user after clicking on a warning icon next to subscription.

**Comment by josh64x2** [comment] 2015-01-26 05:32
@xaka some users have over a thousand subscriptions, so we need to be mindful of that with the dialog. 

I agree that by default we should not destroy user data!

**Comment by xaka** [comment] 2015-01-26 05:39
Exactly, which is why I'm suggesting to display a warning icon as right now, for instance when subscription cannot be retrieved, and after clicking on it, display a dialog. I don't expect it to happen very often and usually it's one-time operation, and you won't be bothered for another year. Actually option might become a key for pandora box and you would end up with another affected user, probably not so friendly :) So I personally would vote against it being part of preferences.

**Comment by josh64x2** [comment] 2015-03-12 23:24
@xaka If I send you a test build, are you able to test this functionality?

Thanks!

**Comment by xaka** [comment] 2015-03-12 23:27
I think I could try. Let's see :)

**Comment by josh64x2** [comment] 2015-03-12 23:50
great! please try the build here http://josh.auspore.com/pub/Vienna.zip
md5sum is `02d9f0bd5510f9c3fafc5e30b3a0fc10`

I haven't tested this build at all other than to make sure the preference is recorded in user defaults correctly. I'll try and get a VM running later with some sort of dodgy proxy to test this.

**Comment by kpfleming** [comment] 2015-03-13 00:30
Another thought: how about storing the *previous* URL when it is changed due to a 301/302 redirect? That way, if the redirect broke the feed, the user can restore it easily by just going into the feed's preferences and recovering the old URL.

**Comment by barijaona** [comment] 2015-03-13 02:58
@kpfleming Very interesting idea, but it is relevant for 301 redirects only, as there is no update to the database after a 302 redirect.

I am still undecided on the adequate user interface for this issue… which is much more geekier than the average user.
Ideally, Vienna should handle everything under the hood, testing back the previous URL in case of problem and restoring in case of success.

**Comment by xaka** [comment] 2015-03-13 05:25
@josh64x2 It works! I've used https://mitmproxy.org/doc/index.html to play around with requests/responses. We should turn on that preference by default ;)

**Comment by josh64x2** [comment] 2015-03-13 05:51
oh excellent! thanks for the link!
Well yes, we have a preference that works now - we just need to work out what to do around defaults etc which is the hard part ;)

**Comment by frankosterfeld** [comment] 2015-04-09 21:57
Same here. I stayed at a hotel (Visit Radisson Blu Hamburg Airport, Hamburg, Germany for the environment it can be reproduced in ;)) and it's stupid login mechanism broke my feeds due to redirects.

Example (adium.im/blog/feed): 

https://auth.netpoint.com/ocs/redirect.asp?port=pp918&host=95067753&mac=6003089766a6&group=%2A&origurl=adium.im%2Fblog%2Ffeed%2F&actasrouter=no&seq=8505bf893f0c59dfa0922360bd731a99&zone=0&sig=76fece621d05ea924db45de77c7c6ff3

**Comment by birdyalex** [comment] 2015-04-20 13:15
the same just happened to me :(
it looks like the original URLs are stored somewhere in the Vienna database  because when I double click on any of my RSS feeds inside Vienna it directs me just right to the desired page but Vienna itself tries to update its RSS feeds using a single wrong address.
is there a way to automatically replace the wrong URLs Vienna uses to update the feeds by URLs it uses after double clicking on the feeds? i have hundreds of RSS feeds so it is almost impossible to replace the URLs by hands... :(

**Comment by barijaona** [comment] 2015-07-17 04:00
@josh64x2 Hello. I understand that you worked at this 301 redirect problem, but you haven't pushed any branch in your Github repository for examination.

My opinion is that very technical issue should remain under the hood. Vienna should not ask the user what to do but guess if the context of the redirection attempt is right.
As a follow-up on one of your proposals, we could test if a call to http://www.example.com/ is also being redirected. If so, the redirection attempt should be considered highly suspicious (section 6.5 of [rfc6761](http://www.iana.org/go/rfc6761 "Special-Use Domain Names")

**Comment by josh64x2** [comment] 2015-07-17 07:15
@barijaona I have updated my code and created PR #462 for discussion.
Currently my code uses a flag (`ignoreHTTP301Redirect` in the `Preference` model) to decide whether or not to updated a feed's URL.
We could have Vienna check a test URL (probably best to use http://vienna-rss.org) and use the result of the test to set the value for `ignoreHTTP301Redirect`. 

Now we have to decide if Vienna must check the test URL at the beginning of every refresh or if Vienna must only check the test URL on start up. 

I prefer checking the test URL at the beginning of every refresh. Consider the following scenario if we only test the URL and set `ignoreHTTP301Redirect` at start up:

1. I am at home with a normal internet connection
2. I open Vienna and the test URL is OK. Vienna sets `ignoreHTTP301Redirect` to NO
3. I put my laptop to sleep without closing Vienna
4. I go to a cafe and wake my computer from sleep
5. I connect to the bad cafe WiFi
6. Vienna starts automatically refreshing feeds and gets an HTTP 301 redirect due to the cafe proxy
7. Vienna checks the value for `ignoreHTTP301Redirect` and sees it is still set to NO from Step 2.
8. Vienna automatically updates all feed URLs with the wrong URL
9. :sob: :angry: 

My only concerns are that checking the test URL at the beginning of every refresh will create delays in refreshing and create a lot of traffic to the test URL.

Thoughts?

**Comment by barijaona** [comment] 2015-07-17 20:33
See my branch [proposal380](https://github.com/barijaona/vienna-rss/commits/proposal380) (untested, and still a bit incomplete)

- Once I have detected a bad network, I consider that all 301 redirects should be considered unsafe for a fixed time (the current implementation is 24 hours ; I think less than 3 hours might be considered abusive as the number of test requests could be )
- I chose to use www.example.com as the test server, because even vienna-rss.org might be down or redirected one day. According to RFC6761, this is very unlikely with example.com, and applications are allowed to use this URL if adequate precautions are taken.

**Comment by barijaona** [comment] 2015-07-18 03:55
Additional thought :
- some redirections might be considered safe and bypass the timer : notably, redirection within the same host
- we could detect when the machine wakes from sleep (with an observer of NSWorkspaceDidWakeNotification) and subsequently reset the timer

**Comment by barijaona** [comment] 2015-07-18 03:56
Additional thought :
- some redirections might be considered safe and bypass the timer : notably, redirection within the same host
- we could detect when the machine wakes from sleep (with an observer of NSWorkspaceDidWakeNotification) and subsequently reset the timer

**Closed** 2015-07-22 09:03 UTC
Labels: Improvement, in progress
