### ISSUE TITLE
Unread Articles count not showing in macOS Ventura

### ISSUE THREAD

**Issue by jazzace** [ViennaRSS/vienna-rss#1621] opened 2022-10-21 16:14 UTC
**Describe the bug**
The Unread Articles folder does not show a count when running under macOS Ventura.

**To Reproduce**
Mark any article from any feed as Unread. The counter showing unread messages for that feed increments by one. The Unread Articles counter is not present. (Note: The badge on the Vienna icon in the Dock correctly shows the unread count. Selecting the Unread Articles folder correctly shows the unread articles.)

**Expected behaviour**
The Unread Articles folder will display the count of all unread articles from all feeds.

**Screenshots**
![Unread Count Missing](https://user-images.githubusercontent.com/4193278/197241427-b355bbfa-14e5-4de0-adde-1161fa33150f.png)

![Unread Articles Still Showing](https://user-images.githubusercontent.com/4193278/197241480-f1c33701-8ddc-4c3b-8fa5-2cefd99dee9b.png)

**Please complete the following information:**
 - Vienna version 3.8.3
 - macOS 13.0 RC 2 (22A380)

**Additional information:**
In which version of Vienna does the problem not occur, if applicable.

**Comment by barijaona** [comment] 2022-10-25 14:25
This is not specific to Ventura or to the Unread folder : unread count is not displayed for smart folders (cf. issue #532)

The problem is that I have not found an elegant approach for dynamically updating the unread count for smart folders.

**Comment by barijaona** [comment] 2023-12-03 14:42
I am reopening issue #532 and closing this one as the wording of the former is more relevant.

**Closed by barijaona** 2023-12-03 14:42 UTC
