### ISSUE TITLE
with new browser, paging down with spacebar an article fails

### ISSUE THREAD

**Issue by phiw13** [ViennaRSS/vienna-rss#1685] opened 2023-05-08 00:21 UTC
Vienna 3.8.7, macOS 13.3.1
Layout type : vertical.

Select any (long) article in the article list, try paging down the page by pressing the spacebar. Noting happens.

Click inside  the article (any blank space) to make sure  there is some focus on the article pane, press the spacebar, same result.

This works fine with the “old” browser

**Comment by barijaona** [comment] 2023-06-28 09:10
I can't reproduce the issue.
Are you sure you were using a 3.8 version when reporting this ?

Space (and Shift-Space) work as expected here.

**Comment by phiw13** [comment] 2023-06-28 11:53
Oh, yes, I was certainly running Vienna 3.8.x at the time - with Mac0S 13.whatever-was-the most-recent-flavor-then. I did test after restarting Vienna and even restarting the OS, and 2 different computers.
That said, yes, with the current version of MacOS 13 and Vienna 3.8.7, it does seem to work  much better. Could it be that some obscure issue at the OS level was actually the cause of the issue at hand?

**Comment by barijaona** [comment] 2023-06-28 16:05
Might be.

I don't remember exactly, but I did tag the issue "Bug" at that time, because I probably acknowledged myself there was a problem.

However, I will close the issue for the time being.

**Closed** 2023-06-28 16:05 UTC
Labels: not reproduced :man_shrugging:

**Comment by barijaona** [comment] 2023-07-01 05:21
Today I learned the existence of the words heisenbug and mandelbug. It reminded me this issue 😉
http://www.catb.org/jargon/html/H/heisenbug.html

http://www.catb.org/jargon/html/M/mandelbug.html

**Comment by TAKeanice** [comment] 2023-07-01 21:02
> http://www.catb.org/jargon/html/M/mandelbug.html

While being familiar with countless heisenbugs, "mandelbug" is a word I didn't know yet. I especially like the schroedingbug which the page links to: "it should never have worked" is something I often think when reading a program source...
