### ISSUE TITLE
Drawing issue in folder list and article view (macOS 10.15)

### ISSUE THREAD

**Issue by phiw13** [ViennaRSS/vienna-rss#1280] opened 2019-12-14 10:05 UTC
Sometimes, when the app has been idle in the background (and hidden, I think) part of the feed-list side bar is not repainted at all leaving blank gaps where feed ought to be. Click in the blank part and some feeds reappear, scroll down/up another blank area, and so on.

I _think_ the issue happens more often when the selected folder is a smart folder.

Vienna latest release, vertical layout, 10.15 Catalina (seen across the various 10.15 releases).
About 150 feeds of which over half are dormant (not actually subscribed).
(MacBookAir 2018).

The issue did not happen before. No other app exhibits anything similar.

a screenshot (taken under 10.15.0):

<img width="775" alt="Vienna sidebar" src="https://user-images.githubusercontent.com/8944809/70847174-974b8480-1ea4-11ea-9f44-a298515d99d8.png">

**Comment by lordgrenville** [comment] 2019-12-15 16:52
I've had this issue with the article viewer as well! Since upgrading to Catalina (I think). When idle in once place for a while it won't repaint below unless I exit and re-enter the specific article. Screenshot:

<img width="655" alt="image" src="https://user-images.githubusercontent.com/16547083/70865952-f9bb8800-1f6b-11ea-89c1-48ce93a10e1e.png">

**Comment by josh64x2** [comment] 2019-12-15 20:15
I also have this issue so I'll be looking into it. I'd appreciate any suggestions though ;)

**Comment by josh64x2** [comment] 2019-12-17 01:31
Could you please let me know which Mac you're experiencing this issue on and whether or not you're using an external monitor? I have this issue on my Late 2012 Mac Mini connected to a Thunderbolt Display but I don't have the issue on my 2015 MacBook Pro 13".

**Comment by phiw13** [comment] 2019-12-17 01:34
As I said, MacBookAir 2018. No external monitors.

**Comment by josh64x2** [comment] 2019-12-17 03:43
OK that's good to know because my theory was to do with older GPU/metal versions and non-retina resolutions. :)

**Comment by lordgrenville** [comment] 2019-12-17 09:23
I'm on a MacBook Pro (Retina, 15-inch, Mid 2015), Catalina 10.15.2. And I _am_ using an external monitor.

**Comment by Eitot** [comment] 2019-12-28 14:29
@phiw13 and @lordgrenville: Are the issues still present in 3.5.5? Have you come across any other apps that have this issue since?

I cannot reproduce the issue myself. I am also not sure what could be causing this. Vienna uses manual drawing only twice and neither pertain to the areas mentioned here. The mention that it is caused after idling may point to a bug in Cocoa itself, which makes it difficult to debug. As both the views are within a table view, I wonder if it is related to the cell-based layout Vienna still uses.

**Comment by josh64x2** [comment] 2019-12-28 23:21
I can't seem to reproduce it on 3.5.5 either...

**Comment by phiw13** [comment] 2019-12-29 08:11
@Eitot  Issue is still there with Vienna 3.5.5.

Only today I saw a  similar issue with a longer article - part of it was no painted. That is something I’ve never seen.

 (at the same time? not sure, the ‘today’ smart folder was selected which is at the top of my feed list)

**Comment by lordgrenville** [comment] 2019-12-29 11:29
Thought I noticed it earlier today, but I've tried to reproduce several times and failed, so I'm going to say it's fixed (in 3.5.5).

**Comment by lordgrenville** [comment] 2019-12-29 12:00
Wait no here it is: 
![Screen Shot 2019-12-29 at 13 58 55](https://user-images.githubusercontent.com/16547083/71556589-77d75e80-2a43-11ea-85bd-12082ac49383.png)

**Comment by Eitot** [comment] 2019-12-29 12:18
The issue @lordgrenville has is particularly weird. That is a web view and it does its own drawing altogether. Is it purely a drawing issue and does the scrolling in that view not work either?

**Comment by lordgrenville** [comment] 2019-12-29 13:01
Yes, as far as I can see the scrolling is totally fixed and the problem remains only in the web view.

**Comment by lordgrenville** [comment] 2019-12-29 14:12
Scrolling as well. I recorded the behaviour in case it helps: http://g.recordit.co/GM8z4hMBCW.gif

**Comment by Eitot** [comment] 2019-12-29 14:50
Judging by the visible scroll view handles, the drawing issue does not seem to occur on the scroll view layer, but one of the layers within it (the clip view or document view). I suppose the same issue occurs in the sidebar, which is a scrollview as well.

I still have no clue what could be causing it, as I have not been able to reproduce it, even with the same layout, style and feed. I will see if something comes up in the debugger while running Vienna.

**Comment by phiw13** [comment] 2019-12-30 00:25
Oops, it did it again… (on the feed list sidebar) - screenshot below.

@Eitot I have only once seen the issue on an article, I’ve tried to reproduce it but no luck so far. It was a longer article, accessed via my “Today” smart folder, arrowing down the article list, then using trackpad to scroll down article itself.

Oh and yes, the scroll view handlers are always visible (when scrolling) and functional. It is really the painting layer that is affected - both the article view and the Feedlist sidebar view.

<img width="303" alt="Screen Shot 2019-12-30 at 9 16 42" src="https://user-images.githubusercontent.com/8944809/71564565-2df38480-2ae6-11ea-8742-e3886cdbf370.png">

**Comment by phiw13** [comment] 2020-01-10 08:37
Question to some of you who don’t seem to suffer from this issue: Do you happen to have the setting “Reduce Transparency” checked? With 10.15 Catalina it is in System Preferences > Accessibility > Display.

I have it off (the default) because the transparency in macOS helps produces softer contrasts and smoother transitions between views which suits _my_ accessibility needs (So, turning it off would be very hard for me, esp as I can’t repro this suite on demand).

I came across the following blogpost, while seemingly unrelated, also mentions transparency on/off as possible cause:

https://eclecticlight.co/2020/01/04/when-apps-show-mirror-writing-upside-down-in-catalina/

**Comment by josh64x2** [comment] 2020-01-13 02:11
I enabled "Reduce Transparency" and I was able to reproduce the bug again. I've turned it off to see if I can get it to trigger again.

**Comment by barijaona** [comment] 2020-01-14 07:57
I am also able to trigger it for the feed list sidebar.

@Eitot, do you have an idea about the best way to debug it in Xcode ?

**Comment by Eitot** [comment] 2020-01-14 12:04
> @Eitot, do you have an idea about the best way to debug it in Xcode ?

No, no specific way. I would have used the view debugger in Xcode (Debug → View Debugging) and checked the console for errors to find some clues. I also have the Quartz Debug tool installed which I would have run as well (bundled in “Additional Tools for Xcode” via Apple Developer).

I have not come across the issue myself, so I cannot really look for clues. I am still searching the web as well. Thus far I only have found this Apple mailing list thread here, which does appear to be the same issue: https://lists.apple.com/archives/cocoa-dev/2019/Dec/msg00021.html. They point to [`NSClipView`’s `copiesOnScroll`](https://developer.apple.com/documentation/appkit/nsclipview/1532142-copiesonscroll) which is deprecated as of Catalina and may cause some unexpected behaviour.

**Comment by josh64x2** [comment] 2020-01-19 02:18
The way I seem to be able to reproduce it is to scroll part of the way down the folder list and then start doing something intensive in another app in front of Vienna without minimising Vienna. After a few minutes when I return to Vienna I then try to scroll the folder list and the issue appears.

**Comment by josh64x2** [comment] 2020-01-19 02:32
Nope, the ProgressIndicator errors have nothing to do with it 😢

**Comment by josh64x2** [comment] 2020-01-31 02:31
Unfortunately this still occurs in 10.15.3 

<img width="244" alt="image" src="https://user-images.githubusercontent.com/799345/73507712-f43bd380-442d-11ea-911d-fdc84c57b234.png">

**Comment by phiw13** [comment] 2020-06-24 09:29
I have the nagging feeling that this issue is fixed due to some fix on Apple’s side. At least I haven’t seen the problem with the feed sidebar since upgrading to 10.15.5.

**Comment by josh64x2** [comment] 2020-06-24 20:32
OK I'll try and reproduce again and see if it has been fixed by Apple...

**Comment by josh64x2** [comment] 2020-06-25 21:49
I couldn't reproduce this on 10.15.5, so I'm going to close it for now as we can always re-open it if someone encounters the issue again.

**Closed by josh64x2** 2020-06-25 21:49 UTC
Labels: bug :bug:
