### ISSUE TITLE
Merge feeds

### ISSUE THREAD

**Issue by evanmiltenburg** [ViennaRSS/vienna-rss#869] opened 2017-04-25 10:35 UTC
I follow several different arXiv feeds, but articles that are cross-listed appear in both feeds. It would be really cool to be able to merge the two feeds and de-duplicate the items that have the same URL.

**Comment by barijaona** [comment] 2018-01-21 06:10
Isn't this a duplicate of #524 ? (and slightly related to #525)

**Closed** 2020-10-12 12:59 UTC
Labels: feature request :bulb:, wontfix
