### ISSUE TITLE
End of sync loses current article from 'Unread Articles' smart folder

### ISSUE THREAD

**Issue by cixonline** [ViennaRSS/vienna-rss#934] opened 2017-07-10 12:52 UTC
This looks like a regression in 3.1.11.

Normally I stay in the Unread Articles smart folder to read unread articles. If I'm reading an article and a sync occurs, then the article I'm reading suddenly disappears from the list. I have the option set to mark articles as read after a short delay which likely contributes to the whole problem. Switching to marking unread after using the Next Unread command would likely fix this, but the current behaviour feels wrong overall. Whatever the user is reading, Vienna shouldn't yank the article out from underneath without warning.

**Comment by Aoiike** [comment] 2017-07-19 08:42
I'm having any Remote Content I currently have open reload when Sync stops, which I think is part of the same issue.

Anything that won't display without a Network Connection seems to be affected, so the entire item if it's set to render as HTML, and embeded items (YouTube, Etc.) when using a Style.
Happens whether Sync is Manual or Automatic (Cancelling Sync also does it) and the Short Delay setting isn't making a difference.
Feeds, Folders, and Smart Folders all behave this way for me. I don't use Open Reader so I haven't tested if that makes a difference.

**Comment by cixonline** [comment] 2017-07-22 07:53
Yes, it is the same issue. When the sync completes, the filters are re-applied. If the message you're viewing isn't within a smart folder or it is but still meets the filter criteria, the article pane is still refreshed. I suspect solving this might be non-trivial but I think it worth looking into just for that extra bit of polish in the user experience.

**Comment by barijaona** [comment] 2017-07-28 20:39
@cxonline, what version of Vienna were you using before ?

The two problems are not completely identical, but are related to recent changes to the same class (ArticleController).

**Comment by cixonline** [comment] 2017-07-29 06:54
Not sure what the earlier version was, sorry. 3.1.9, possibly.

**Comment by z00ber** [comment] 2017-08-09 19:46
I have the same issue as cixonline. Current article disappears when sync occurs (smart folder with filtering on unread articles). I'm not sure if the issue was there before 3.1.11 .
Technically its not unread anymore when the sync is done of course, but often I haven't finished reading the article...

**Comment by DavidMunch** [comment] 2017-08-10 17:15
Related to #829 ?

**Comment by z00ber** [comment] 2017-08-10 18:08
Not sure if it is related or two different bugs.
I can verify that when following the description in #829 I get the same problem as described.

**Comment by vr8hub** [comment] 2017-09-01 16:29
Any movement on this? This behavior (and it is a regression in 3.1.11) is really interfering with my use of Vienna.

**Comment by lapcat** [comment] 2017-09-02 17:34
This issue seems to have started with https://github.com/ViennaRSS/vienna-rss/commit/4b3a8632efc32669c191ad81b89d7cc7705a3154

**Comment by barijaona** [comment] 2017-09-02 17:39
Hi Jeff ! Nice to have you back on boat. Can you review pull request #987 ?

**Comment by barijaona** [comment] 2017-09-04 01:53
Closed by 3.1.12

**Closed** 2017-09-04 01:52 UTC
Labels: bug, critical

**Comment by vr8hub** [comment] 2017-09-05 14:47
3.1.12 does not fix this. The behavior is still there — click on a new article while Vienna is still refreshing, and when it finishes refreshing, the article you're reading is moved out of Unread out from under you.

**Comment by cixonline** [comment] 2017-09-05 16:46
Confirmed here too. Just to be clear, this is with "Mark current article read: After a short delay" so the article being read will have the read flag set.
