### ISSUE TITLE
Some feeds display the previous item instead of the newest on updates.

### ISSUE THREAD

**Issue by dak180** [ViennaRSS/vienna-rss#452] opened 2015-06-20 17:21 UTC
https://kerbalstuff.com/mod/532.rss is a good example of this but any feed on that site should show these symptoms.

**Comment by barijaona** [comment] 2015-08-22 16:07
I cannot reproduce the problem now. Did you have a backup of the feed at that time ?

**Comment by dak180** [comment] 2015-08-22 16:24
Unfortunately no; however it is a continuing issue with literally every feed on that website that I have checked, so it should be easy enough to pick out an example from one of them.

**Comment by barijaona** [comment] 2015-08-27 00:42
These feeds are particularly ugly : the worst problem is that they use the same `guid`value for all items in a feed.

Vienna has some workarounds to handle these problems, but I am unsure I can improve on it without creating other problems.

**Comment by barijaona** [comment] 2015-09-13 10:06
Fixed by commit e53a0c3b4079ea49a194b4a00389f8149b8416d4

**Closed by barijaona** 2015-09-13 10:06 UTC
Labels: Improvement
