### ISSUE TITLE
Mark as read only works halfway on newest 3.9 release

### ISSUE THREAD

**Issue by mlcampbe** [ViennaRSS/vienna-rss#1727] opened 2024-01-23 17:13 UTC
**Describe the bug**
Prior to version 3.9 I could use (on my Mac) the command-k shortcut to mark all articles read. This inly works partly now in 3.9. I can still see that the number of unread articles on the sidebar list changes to zero but the articles shown in the right-hand pane are still showing the title in a bold font like an unread article. 

Additionally if I use a filter to change between "all" and "unread" articles the righthand pane still shows all of the same ones in bold.

**To Reproduce**
Have a list of unread articles and press cmd-k

**Screenshots**
Add screenshots to help explain your problem, if possible.

**Please complete the following information:**
 - Vienna version 3.9
 - OS version: 14.2.1

**Additional information:**
In which version of Vienna does the problem not occur, if applicable.
Just started this behavior with the new 3.9 release.

**Comment by briandfoy** [comment] 2024-01-24 17:56
I experience the same problem. 

I also have a Smart Folder for all articles where `is read` is `no`. I can control click  to get the contextual menu that includes "Mark All Articles as Read". When I do that, the article list pane does not update. If I choose another folder then come back to my Smart Folder, it shows all the articles as read. This seems like the article list fails to update even though they are correctly marked as read.

**Comment by mlcampbe** [comment] 2024-01-24 17:57
I'll note that I have found that if you click the refresh button after using cmd-k then the right-hand pane will clear and there are no articles shown. In the past pressing cmd-k would mark all as read and then refresh the display as well.

**Comment by josh64x2** [comment] 2024-01-25 02:00
I haven't been able to reproduce the original issue with the font staying bold when you press ⌘k, however I was able to reproduce the issue with the smart folder with both the keyboard shortcut and the contextual menu.

**Comment by briandfoy** [comment] 2024-01-25 05:04
Btw, this is a bug, but it's not really bothering me since I check Vienna once a day. I know that the articles will be marked correctly, and since my usual next step is to quit Vienna, I don't need to see the pane updated. I can be patient for a fix. Other people may have different needs though. I should have noted that initially and I've felt a bit guilty about not mentioning that I don't want anyone to lose sleep to fix this right away for me.

**Comment by barijaona** [comment] 2024-02-18 14:11
Could you please specify which filter is set when you observe that behavior ?

**Comment by briandfoy** [comment] 2024-02-18 18:44
In my case, the filter pull down says "All Articles" when I'm in my Smart Folder for `is_read` is `no`. I don't mess around with filters, so everything is whatever the default it.

**Comment by mlcampbe** [comment] 2024-02-20 14:16
> Could you please specify which filter is set when you observe that behavior ?

For me I normally use the "unread articles"  on the left-hand side panel while the is set for "all articles". 

As briandfoy mentioned "If I choose another folder then come back to my unread Folder, it shows all the articles as read. "

**Comment by makigumo** [comment] 2024-04-05 19:48
I maybe wrong but it seems the following line should also check for `|| currentFolder.type ==  VNAFolderTypeSmart`.
https://github.com/ViennaRSS/vienna-rss/blob/7ad9df04487410600484cbd2ca4e82e25de7b7c7/Vienna/Sources/Main%20window/ArticleController.m#L885
This seems to fix the issue with smart folders not visually updating for me.

**Comment by hphde** [comment] 2024-04-16 10:59
> Btw, this is a bug, but it's not really bothering me since I check Vienna once a day. I know that the articles will be marked correctly, and since my usual next step is to quit Vienna, I don't need to see the pane updated. I can be patient for a fix. Other people may have different needs though. I should have noted that initially and I've felt a bit guilty about not mentioning that I don't want anyone to lose sleep to fix this right away for me.

I have the same issue on MacOS 14.4.1 with Version 3.9.0 :7ad9df044: (8175) - marking all read has no visible effect. Clicking on an article flags it visibly read. Refreshing or switching to another view and back updates it.

**Comment by barijaona** [comment] 2024-06-23 05:01
@makigumo can you confirm that the problem is fixed for you in current master ?

**Comment by makigumo** [comment] 2024-06-23 12:02
I could build it successfully after updating the MMTabBarView dependency to `v/1.5.3` (I'm using macOS 15 beta with Xcode 16 beta). But it crashes because it can't find `libswiftCoreGraphics.dylib`. I was able to run it, after manually putting a copy of `libswiftCoreGraphics.dylib` into `Vienna.app/Contents/Frameworks/lib/`.

Test result: works as expected 👍

**Comment by josh64x2** [comment] 2024-06-27 07:12
> I could build it successfully after updating the MMTabBarView dependency to `v/1.5.3` (I'm using macOS 15 beta with Xcode 16 beta). But it crashes because it can't find `libswiftCoreGraphics.dylib`. I was able to run it, after manually putting a copy of `libswiftCoreGraphics.dylib` into `Vienna.app/Contents/Frameworks/lib/`.
> 
> 
> 
> Test result: works as expected 👍 

The issue with `libswiftCoreGraphics.dylib` is apparently fixed in Xcode 16 beta 2. Are you able to confirm?

**Comment by makigumo** [comment] 2024-06-27 11:16
> The issue with `libswiftCoreGraphics.dylib` is apparently fixed in Xcode 16 beta 2. Are you able to confirm?

I can confirm, with Xcode 16 beta 2 I'm able to run Vienna.app without the workaround.

**Comment by barijaona** [comment] 2024-07-12 04:36
Closed by Vienna 3.9.1

**Closed by barijaona** 2024-07-12 04:36 UTC
Labels: bug :lady_beetle:
