### ISSUE TITLE
EnclosureView contracts to shortest width

### ISSUE THREAD

**Issue by jeanravin** [ViennaRSS/vienna-rss#1082] opened 2018-02-06 13:12 UTC
Since 3.2.1 (using macOS 10.10.5) I have this bug happening only on articles with linked files , if I click an article the right column is retracted to the far right. If I try to resize it, it will still collapse to the right.

![2018-02-06015822 vienna-vienna](https://user-images.githubusercontent.com/1174299/35860956-5919872a-0b46-11e8-850d-e925af55aef8.png)

**Comment by Eitot** [comment] 2018-02-08 17:04
Can you share the feed URL?

**Comment by jeanravin** [comment] 2018-02-08 17:13
Here it is : http://feeds.feedburner.com/Kerozene

**Comment by mvilain** [comment] 2018-02-08 22:16
I can confirm this problem on 10.10.5.  It's why a downgraded to Vienna 3.1.16.  I'll stay there until this is fixed.

**Comment by Eitot** [comment] 2018-02-10 08:29
This appears to be isolated to particular versions of macOS. I cannot confirm this on Sierra nor High Sierra. I am guessing that this is an Auto Layout issue with the stack view.

**Comment by mu-is-too-short** [comment] 2018-02-10 19:37
I'm seeing the same issue on macOS 10.10.5 with Vienna 3.2.1 on:

    http://feeds.feedburner.com/tedtalks_video

Vienna 3.2.0 seems fine with it.

**Comment by jeanravin** [comment] 2018-02-10 19:41
> Vienna 3.2.0 seems fine with it.

Indeed.

**Comment by Eitot** [comment] 2018-02-10 19:48
That is bizarre. There are barely any changes between 3.2.0 and 3.2.1, at least none that touch upon the UI there.

**Comment by mvilain** [comment] 2018-02-10 19:51
Tired to get into the CocoaForge Forum but it didn't like the antispam question, so forgetaboutit.

Anyway, these are all moot since I can't build form 3.2 sources and there's only the beta binary.  Unless there's an offical 3.2 binary somewhere, I'm sticking to 3.1.6 until this is fixed on 10.10.5.

**Comment by jeanravin** [comment] 2018-02-10 20:02
@mvilain https://github.com/ViennaRSS/vienna-rss/releases

**Comment by rawtaz** [comment] 2018-02-10 20:09
It's happening for me on an OS X 10.9.5 machine as well, so it's not just OS X 10.10.5. Same there, started after upgrading from 3.2.0 to 3.2.1.

**Comment by josh64x2** [comment] 2018-02-11 02:41
I just tested on a VM for 10.10.5 and I was able to reproduce. This was with version 3.2.0 beta 1.
When I try to resize the columns it snaps straight back to the bad layout similar to the screenshot in the main issue.

Unfortunately there is nothing in the logs.

**Comment by barijaona** [comment] 2018-02-11 04:50
Is it possible to examine the preferences file ?

**Comment by josh64x2** [comment] 2018-02-11 07:57
Here you go :) 
[uk.co.opencommunity.vienna2.plist.zip](https://github.com/ViennaRSS/vienna-rss/files/1714156/uk.co.opencommunity.vienna2.plist.zip)

**Comment by Eitot** [comment] 2018-02-11 18:34
I think I have come up with a solution. It was a misconfiguration of the labels in Interface Builder.

**Comment by barijaona** [comment] 2018-02-20 13:28
Does the problem appear in 3.2.1 only ? I see no reason for the problem to appear in 3.2.1 and not in 3.2.0

**Comment by rawtaz** [comment] 2018-02-20 13:30
@barijaona Yes, it happens in 3.2.1 but not in 3.2.0, and this is for multiple people on different versions of OS X/macOS.

**Comment by barijaona** [comment] 2018-02-20 13:33
@mvilain You wrote you stick with 3.1.16 for the time being. Did you try 3.2.0 and notice this problem with it ?

**Comment by rawtaz** [comment] 2018-02-20 13:35
@barijaona FWIW, I have both 3.2.0 and 3.2.1 installed. The former works fine, the latter doesn't. I'm not sure why you have a hard time agreeing it started happening after 3.2.0.

**Comment by rawtaz** [comment] 2018-02-20 13:41
@Eitot Can you elaborate - is a fix submitted anywhere, perhaps even merged to master?

**Comment by barijaona** [comment] 2018-02-20 13:45
@rawtaz because when I compare [3.2.1 source to 3.2.0](https://github.com/ViennaRSS/vienna-rss/compare/v/3.2.0...v/3.2.1), I see strictly no change related to this specific window.

**Comment by rawtaz** [comment] 2018-02-20 14:16
@barijaona Right, I understand that. Other devs said the same if you read above. Despite that though, there's no disputing that the problem started happening with 3.2.1. It's not likely that it's just a random coincidence that it started happening with that specific version for multiple people on multiple platforms. Let's see what @Eitot replies, as he said he found the problem and fixed it.

**Comment by Eitot** [comment] 2018-02-20 17:17
I thought I had fixed it, but it caused other issues elsewhere. Then I found out that sometimes to solution worked and sometimes it didn’t, even between builds. I am suspecting that there might be something else, perhaps a build issue. That would explain why this problem started appearing only in 3.2.1, even though the source did not even touch the XIB file.

**Comment by mu-is-too-short** [comment] 2018-02-20 17:28
@barijaona I see a layout resizing problem with Vienna 3.2.1 on macOS 10.10.5, Vienna 3.2.0 works fine. I don't see the exact problem problem as jeanraven though, my left and right panes keep resizing themselves to be the same width when there's an attachment. I'm using the Horizontal layout and FeedLight Aqua style if that's relevant.

**Comment by barijaona** [comment] 2018-02-21 01:34
A build issue is possible, as I have recently noticed some mysterious problems that could be solved by removing and rebuilding my `~/Library/Developer/Xcode/DerivedData/ModuleCache/` folder. I have rebuilt a 3.2.1 here. Can you try it ?


[Vienna3.2.1.tar.gz](https://github.com/ViennaRSS/vienna-rss/files/1742523/Vienna3.2.1.tar.gz)

**Comment by mu-is-too-short** [comment] 2018-02-21 04:10
@barijaona I just tried that build of 3.2.1 and it seems to be behaving itself for me. Nice one.

**Comment by jeanravin** [comment] 2018-02-21 09:51
@barijaona I confirm, this build fix the bug.

**Comment by barijaona** [comment] 2018-02-22 02:42
The new build has been uploaded to Github, Sourceforge and Bintray.

**Comment by rawtaz** [comment] 2018-02-22 09:56
The new build solved the problem on OS X 10.9.5. Thanks!

**Comment by jeanravin** [comment] 2018-04-01 13:58
Oops, it's happening again with 3.3.0 …

**Comment by rawtaz** [comment] 2018-04-01 13:59
Same here, same symptoms, with 3.3.0.

**Comment by barijaona** [comment] 2018-04-01 14:57
A corrupted cache during build again ? Could you try this one ?
[Vienna3.3.0.tar.gz](https://github.com/ViennaRSS/vienna-rss/files/1866419/Vienna3.3.0.tar.gz)

**Comment by jeanravin** [comment] 2018-04-02 17:11
@barijaona Alas, still not behaving correctly here… Staying with 3.2.1 for now.

**Comment by barijaona** [comment] 2018-04-02 17:14
@jeanravin you are still running 10.10.5 ?

**Comment by rawtaz** [comment] 2018-04-02 17:15
FWIW, 10.9.5 here, same problem.

**Comment by jeanravin** [comment] 2018-04-02 21:30
@barijaona still

**Comment by barijaona** [comment] 2018-12-14 20:49
Apparently problem reappeared in 3.5.1 but is not present in 3.5.0
https://forums.cocoaforge.com/viewtopic.php?t=27111
https://forums.cocoaforge.com/viewtopic.php?t=27117

**Closed** 2020-10-12 12:59 UTC
Labels: bug :bug:, wontfix
