### ISSUE TITLE
Title with emoji are bad displayed in the titles list

### ISSUE THREAD

**Issue by quark67** [ViennaRSS/vienna-rss#516] opened 2015-09-24 23:03 UTC
For example, in this feed : https://littlebitesofcocoa.com/rss all titles contains an emoji character. The titles are truncated vertically and unreadable.

I use : Vienna version 3.0.8 :074a131(last version yet).

![capture d ecran 2015-09-25 a 00 53 11](https://cloud.githubusercontent.com/assets/9338576/10089083/1e33a030-6320-11e5-8ca4-5f555fb33449.png)

Other example with this feed : http://krakendev.io/?format=rss

![capture d ecran 2015-09-25 a 01 00 12](https://cloud.githubusercontent.com/assets/9338576/10089157/dda6863a-6320-11e5-847d-b620c22acd05.png)

**Comment by phiw13** [comment] 2015-09-26 13:02
That is the same problem as issue #447.

**Comment by bhagyas** [comment] 2015-10-21 11:51
+1

**Comment by josh64x2** [comment] 2015-10-21 22:00
The affects horizontal layout

**Comment by barijaona** [comment] 2016-11-27 22:45
Duplicate of #447

**Closed by barijaona** 2016-11-27 22:45 UTC
Labels: bug
