### ISSUE TITLE
Version 3.9.0 changing subscription list to alphabetical order. 

### ISSUE THREAD

**Issue by liamgreenwood** [ViennaRSS/vienna-rss#1732] opened 2024-01-28 01:41 UTC
**Describe the bug**
I upgraded to Version 3.9.0 :7ad9df044: (8175) and Vienna reordered my subscription list to alphabetical order.  I reset all my subscriptions to the order I want by restoring the opml subscription list form my last save but Vienna again reset the order to alphabetical with groups at the top. The previous version didn't mess with the order of my subscriptions - everything stayed in the position I set them to.

**To Reproduce**
I just reset the order and sometime in the following 24 hours Vienna re-orders them to alphabetical
**Screenshots**
Add screenshots to help explain your problem, if possible.

**Please complete the following information:**
 - Vienna Version 3.9.0 :7ad9df044: (8175)
 - OS version: Sonoma 14.3 (23D56)

**Additional information:**

**Comment by barijaona** [comment] 2024-06-26 06:45
Closing this as it is a duplicate of #1743

**Closed by barijaona** 2024-06-26 06:45 UTC
